### ISSUE TITLE
Failed opening required 'abstract.php' 

### ISSUE THREAD

**Issue by satyapackirisamy** [thaiphan/magento-s3#10]
I Uploaded the module in my magento, when i try to run the script it shows the below error:

PHP Warning:  require_once(abstract.php): failed to open stream: No such file or directory in /magento/shell/s3_config.php on line 2
PHP Fatal error:  require_once(): Failed opening required 'abstract.php' (include_path='.:/usr/share/php:/usr/share/pear') in /magento/shell/s3_config.php on line 2

**Comment by thaiphan** [comment]
Hi @satyapackirisamy,

How did you install the extension? Did you install using Composer?

Regards,

Thai

**Comment by thaiphan** [comment]
Hi @satyapackirisamy,

Have you done the configuration step of the instructions yet?

https://github.com/thaiphan/magento-s3/wiki/Installation#step-1-configure-magento-to-use-your-s3-bucket

Regards,

**Comment by satyapackirisamy** [comment]
Hi @thaiphan 

I have done the fist step of configuration.

I run the script "php s3_config.php \ --access-key-id xxxxxxxxxxxxxxx \    --secret-key xxxxxxxxxxxxxxxxxxxxxx \    --bucket magento-mumbai \ --region ap-south-1" inside the shell folder.

**Comment by satyapackirisamy** [comment]
@thaiphan 

Please help me. I need your help so deep

**Comment by thaiphan** [comment]
Hi @satyapackirisamy,

Okay I know your problem. As described in #4, my extension doesn't support the Bombay region at the moment sorry. :(

I'll try and see if I can build it this weekend. Best I can do.

Regards,

Thai

**Comment by thaiphan** [comment]
Hey @satyapackirisamy,

I'm closing this issue because I'm tracking it in #4 already. I hope that's okay.

Regards,

Thai

**Comment by satyapackirisamy** [comment]
@thaiphan 

Thank you for your reply.

And if you can able to so it for mumbai region please do it for me. It could save my life. 

Thanks and regards,

Satya
