### ISSUE TITLE
Image not uploading to s3 bucket when trying to upload catalog images from back-end.

### ISSUE THREAD

**Issue by ajayshukla** [thaiphan/magento-s3#11]
When I run export.php file from the shell, all my images are getting uploaded to s3bucket, but when I try to upload image for a specific product, image is not uploading,  can you please let me know what I need to do to fix this?

**Comment by thaiphan** [comment]
Hey @ajayshukla,

Are you using the latest version of my extension? What version of Magento are you using?

Can you take a screenshot of your attempt to upload an image?

Regards,

Thai

**Comment by ajayshukla** [comment]
Thanks for your quick reply.

I am using your latest extension on magento 1.9.3. Here is the screenshot http://nimb.ws/gwvKZH that is image is not getting uploaded to s3bucket from magento admin catalog image upload section. 

In magento media folder it is going there. Also, can you please let me know how can I optimize the images while uploading to s3bucket and after image gets uploaded we don't want to keep the copy on our server that is inside magento/media folder.

**Comment by ajayshukla** [comment]
May, I know how can I do this:
_With the screenshot that you've provided, it potentially looks like you haven't updated your web server configuration to route all /media requests to get.php._

Also, when I run the s3_enable.php from shell, I am getting this error:-

_PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mysql.so' - /usr/lib/php/20151012/mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0_

Also because of the above error, I suppose the db changes are not done and this I have to change the Base Media URL http://nimb.ws/Nyoblv

So, please let me know the solution for this as well.

**Comment by thaiphan** [comment]
Hi @ajayshukla,

Are you running `s3_enable.php` from the same server as your Magento?

Regards,

Thai

**Comment by ajayshukla** [comment]
Yes, I am running from the same server as my Magento setup.

**Comment by thaiphan** [comment]
Are you using Apache or Nginx?

**Comment by ajayshukla** [comment]
I am using Apache.

**Comment by ajayshukla** [comment]
Any news on this Thai?

> With the screenshot that you've provided, it potentially looks like you haven't updated your web server configuration to route all /media requests to get.php. Once you do that, I think images should start showing up.

**Comment by thaiphan** [comment]
Hi @ajayshukla,

Yeah, I was at work.

Do you have a server guy that you can go to? Providing support for web server configuration really isn't something that I want to be doing.

Also, can you go back to the image upload page and show me what it says in the Network tab in your Chrome console?

Regards,

Thai

**Comment by ajayshukla** [comment]
![image](https://user-images.githubusercontent.com/1754220/40427672-06ef9844-5ebc-11e8-9b98-062b4d7a4e7a.png)

**Comment by ajayshukla** [comment]
HelloThai,

I got the solution today. What I did is that I ran s3_enable.php file from shell like this php s3_enable.php y and it started working.

There is still one problem that when I try to upload the images from some admin grid edit form file field, it is not uploading to s3. Is there anything extra I need to do?

I am attaching the input type file here. So, please let me know what we can do for such file fields?

Thanks
![screenshot1](https://user-images.githubusercontent.com/1754220/40488782-2cbfc80e-5f85-11e8-8883-84759f527b1e.png)

**Comment by thaiphan** [comment]
This looks like a third party extension. Sometimes they don't do file uploads the Magento way. Is it open source? I can review the code

**Comment by ajayshukla** [comment]
Yes this is the custom module. You can see the code of this magento module from here https://github.com/ajayshukla/Image-Gallery

**Comment by thaiphan** [comment]
Hey @ajayshukla,

It looks like this extension is hardcoded to use the file system storage so it won't upload to S3 at all:

https://github.com/ajayshukla/Image-Gallery/blob/master/app/code/local/Webkul/Agorae/controllers/Adminhtml/ImagesController.php#L41

I'd recommend going back to Webkul and asking if they can update their extension to be more flexible. My extension uses the built-in Magento database file storage mechanism so if you ask them to support that, they might be able to help out.

I'm also willing to update this extension as well but only for a price.

Regards,

Thai

**Comment by thaiphan** [comment]
Hey @ajayshukla,

Let me know how you go in a new issue. I'm closing this one since the original problem got resolved!

Regards,

**Comment by jiitpiyush** [comment]
Hi @thaiphan, I checked your code and added the ap-south-1 region to the helper, but still, the issue persists as media is not uploading to S3. Can you please guide me where to debug?

**Comment by jiitpiyush** [comment]
any updates?

**Comment by ajayshukla** [comment]
Hello Piyush,

Regarding this "Hi @thaiphan, I checked your code and added the ap-south-1 region to the helper, but still, the issue persists as media is not uploading to S3. Can you please guide me where to debug?"
, are you getting this error for new image for catalog or for old images which were uploaded earlier?

**Comment by jiitpiyush** [comment]
I'm getting this error for new catalog/product images .

**Comment by jiitpiyush** [comment]
any updates?

**Comment by thaiphan** [comment]
Hi @jiitpiyush,

Yeah sorry, work is always a distraction. Unfortunately, as described in #4, my extension currently doesn't support V4 Signature regions such as Bombay. I'll make an attempt this weekend add support but it's pretty complicated.

Please use #4 to track the progress of this.

Regards,

Thai

**Comment by piyushs02** [comment]
Thank you for letting me know @thaiphan. I shifted my bucket location to us-east-1 and now its working fine. Great work.

**Comment by vinayramgokul** [comment]
will this plugin work for 2.4.5 ? @thaiphan
