### ISSUE TITLE
Error during unserialisation

### ISSUE THREAD

**Issue by jiitpiyush** [thaiphan/magento-s3#12]
When uploading images to a product, I'm getting an error during serialization.
![screenshot from 2018-05-26 19-51-27](https://user-images.githubusercontent.com/6623208/40577170-bcf8776e-611e-11e8-8256-41b47bcbe955.png)

This issue exists after the new pull on May 26, 2018 (last commit id a154467e72b77db52ad51cd0f0b445d6f3afbdac).

**Comment by thaiphan** [comment]
Hey @jiitpiyush,

Thanks. It looks to be a problem with the new metadata feature I added the other day. :/ I'll get back to you soon.

Regards,

Thai

**Comment by thaiphan** [comment]
Hey @jiitpiyush,

I've just pushed up a new version that should address your problem. Can you install and review?

Regards,

Thai

**Comment by jiitpiyush** [comment]
Hi @thaiphan ,
Thank you for your instant reply and bug resolution. That bug is resolved but images are not getting uploaded to my s3-bucket. can you plz look into that?

**Comment by thaiphan** [comment]
Were you successfully uploading previously or did it stop working with the latest change?

**Comment by jiitpiyush** [comment]
I take first pull from your repo yesterday and I'm getting issues.

**Comment by thaiphan** [comment]
@jiitpiyush So you installed the extension for the first time yesterday?

**Comment by jiitpiyush** [comment]
My region is ap-south-1

**Comment by jiitpiyush** [comment]
Hi @thaiphan, I checked your code and added ap-south-1 region to helper , but still issue persist as media is not uploading to S3. Can you please guide me where to debug?
,

**Comment by thaiphan** [comment]
Hi @jiitpiyush,

I think this is a continuation of #4. I'm using Magento's built-in S3 client, which is super old and doesn't support the new V4 Signature Signing. It only supports V2 for the time being. The `ap-south-1` region only supports V4 so you unfortunately won't be able to use that region.

Regards,

**Comment by thaiphan** [comment]
Hey @jiitpiyush,

I'm closing this issue because I'm tracking it in #4 already. I hope that's okay.

Regards,

Thai
