### ISSUE TITLE
I need to use S3 like media origin on CloudFront

### ISSUE THREAD

**Issue by rcicero** [thaiphan/magento-s3#13]
I tried to use S3 with media origin on CloudFront, but it don't work. I saw that the problem is I need creat a directory in S3 called media and save files into directory. Can I set the plugin for do this? Today the plugin save all files in the root of S3 and CloudFront don't work better with this.

**Comment by thaiphan** [comment]
Hi @rcicero,

I have updated this extension (v1.3.0) to support prefixes. Hopefully that should resolve the issue that you have raised. If not, feel free to re-open the ticket.

Also, if you enjoy my extension, please consider making a small donation to help support my work. https://www.paypal.me/thaiphan

Regards,

Thai
