### ISSUE TITLE
Files keep on local storage

### ISSUE THREAD

**Issue by AndrewMarques** [thaiphan/magento-s3#14]
Hi @thaiphan, I'm using your module, thanks for it.

I have a question, why do files stay in local storage? How do I send just for s3?

**Comment by greatwitenorth** [comment]
@AndrewMarques Did you find a solution to this? I'm still seeing files being downloaded locally despite following the directions in the readme regarding (updated static url to point to s3).

**Comment by meer-online** [comment]
@greatwitenorth @thaiphan @AndrewMarques  Did any of you figure out the issue with this or were able to fix it?
