### ISSUE TITLE
App config export exporting sensitive information

### ISSUE THREAD

**Issue by chocolatethunder** [thaiphan/magento-s3#16]
When running 
```bash
php bin/magento app:config:dump
```
The S3 access keys are being exported to the config.php and not env.php

This is causing deployment pipeline issues because config.php is supposed to be part of version control and env.php is not. Don't want to accidentally publish my AWS data to Github.

Additionally, I have also tried adding this to app/etc/di.xml file
```php
<type name="Magento\Config\Model\Config\TypePool">
   <arguments>
      <argument name="sensitive" xsi:type="array">
         <item name="thai_s3/general/access_key" xsi:type="string">1</item>
         <item name="thai_s3/general/secret_key" xsi:type="string">1</item>
      </argument>
   </arguments>
</type>
```
But it doesn't affect the config export.

**Comment by thaiphan** [comment]
Hi @chocolatethunder 

This repo is for the Magento 1 extension. Can you re-create this issue in the Magento 2 repo below?

https://github.com/thaiphan/magento2-s3/

Regards,

Thai

**Comment by chocolatethunder** [comment]
Hey @thaiphan 

My apologies. Had a million tabs open so I posted the issue in the wrong repo. This issue is happening with the Magento2-S3 plugin. I will post a new issue there.
