### ISSUE TITLE
Is there any way to sync custom module image directory in to s3?

### ISSUE THREAD

**Issue by Erchiragdodia** [thaiphan/magento-s3#3]
How can i upload custom module images to s3? is there any piece of code need to change?

**Comment by thaiphan** [comment]
Hi @Erchiragdodia,

If you use the Magento's built-in file storage mechanisms in your code, the extension should be able to just upload to S3. What extension were you using? I can double check.

Regards,

Thai

**Comment by VivekShingala** [comment]
Hi @Erchiragdodia 

Did you find a way to use the Magento's built-in file storage mechanisms in a custom module? If so, could you please share it here?
