### ISSUE TITLE
Running the command returns blank

### ISSUE THREAD

**Issue by acoustep** [thaiphan/magento-s3#5]
First of all, thank you for creating this plugin!

I'm following the instructions on the installation page and using composer to install it.
When I try running the s3_config.php / s3_export.php  ( located in vendor/thaiphan/magento-s3/shell ) I'm getting no response from the commands.

I look at the code and it's looking for a `./abstract.php` which doesn't seem to exist in the directory? The command doesn't seem to run anything past that line.

Am I missing something?

Thanks

**Comment by thaiphan** [comment]
Hi @acoustep,

You're meant to run s3_config.php from your Magento root shell folder! For example,

/path/to/magento/shell/s3_config.php

Are you finding that the file isn't there? That might indicate that you don't have the [Magento Composer Installer extension](https://github.com/Cotya/magento-composer-installer) installed.

Regards,

Thai

**Comment by acoustep** [comment]
Hi @thaiphan, thanks for the quick response! You're right I don't have the Magento Composer installer extension. I'll try that now.

**Comment by acoustep** [comment]
Sorry about this - I thought this was for Magento2. I've switched to your other plugin now and it's working 🙂
