### ISSUE TITLE
Missing Expiry Header

### ISSUE THREAD

**Issue by vinitchopra12** [thaiphan/magento-s3#6]
I have installed the module and sync the media folder till its working fine. But I have noticed that all the images uploaded on the S3 have no Expiry header.
So I am wondering how I can set the Expiry header for each images (pre-existing and new upload).

**Comment by thaiphan** [comment]
Hi @vinitchopra12,

Sorry for the very late reply.

I have added a feature to the Magento admin panel that lets you send through the custom headers to S3. This is available in the latest version of this extension.

Regards,

Thai
