### ISSUE TITLE
Images automaticaly get added to Media folder

### ISSUE THREAD

**Issue by Vishrootways** [thaiphan/magento-s3#7]
Hello,

We have set up this module on our one of the magento website. We have deleted all images from magento media folder and uploaded to Amazon S3. It's working.

The issue is when a user opens product detail page, images automatically get added to Magento media folder. How to stop this?

**Comment by kanevbg** [comment]
Hi there, the solution is in the readme:

https://github.com/thaiphan/magento-s3#magento-is-still-loading-images-from-the-file-system-what-went-wrong

**Comment by thaiphan** [comment]
Thanks @kanevbg for assisting with this query!

**Comment by meer-online** [comment]
@kanevbg Already followed what was mentioned inside the readme but that didn't help. Any other solution that comes to your mind?

@Vishrootways Were you able to get around this issue?
