### ISSUE TITLE
I am having trouble inserting a new image by CMS.

### ISSUE THREAD

**Issue by luciosribeiro** [thaiphan/magento-s3#8]
Follow the error message.

`[Thu Feb 22 11:48:34.923739 2018] [:error] [pid 2936] [client ::1:40070] PHP Fatal error:  Uncaught Error: Call to undefined method Zend_Service_Amazon_S3::getObjectsAndPrefixesByBucket() in /magento/path/app/code/community/Thai/S3/Model/Core/File/Storage/S3.php:231\nStack trace:\n#0 /magento/path/app/code/community/Thai/S3/Model/Cms/Wysiwyg/Images/Storage.php(29): Thai_S3_Model_Core_File_Storage_S3->getDirectoryFiles('/home/lucio/pro...')\n#1 /magento/path/app/code/core/Mage/Adminhtml/Block/Cms/Wysiwyg/Images/Content/Files.php(51): Thai_S3_Model_Cms_Wysiwyg_Images_Storage->getFilesCollection('/home/lucio/pro...', NULL)\n#2 /magento/path/app/code/core/Mage/Adminhtml/Block/Cms/Wysiwyg/Images/Content/Files.php(65): Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Content_Files->getFiles()\n#3 /magento/path/app/design/adminhtml/default/default/template/cms/browser/content/files.phtml(38): Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Content_Files->getFilesCount()\n#4 /magento/path/app/code/core/Mage/Core/Block/Template.php(241): include(' in /magento/path/app/code/community/Thai/S3/Model/Core/File/Storage/S3.php on line 231, referer: http://localhost/magento/index.php/duit/cms_block/new/key/2b691fe51fed06b9c5ba865fbc2afa7a/`

**Comment by thaiphan** [comment]
Hi @luciosribeiro,

Sorry for the late reply. Did you figure out this problem? What version of Magento are you using?

Regards,

Thai

**Comment by thaiphan** [comment]
Hi @luciosribeiro,

Okay, so I've identified the problem and have released a new version with a hotfix that should fix that problem!

Regards,

Thai

**Comment by luciosribeiro** [comment]
Thanks, @thaiphan!
